return {
  onboardingComplete = false,
  updateInterval = 0.10,
  telemetryPeripheral = nil,
  monitorPeripheral = nil,
  gps = {
    enabled = true,
    timeout = 0.5,
  },
  safety = {
    maximumOutput = 5,
    maximumRemotePulse = 2.0,
    disengageOnTelemetryLoss = true,
    clearOutputsOnExit = true,
  },
  navigation = {
    cruiseSpeed = 12,
    approachSpeed = 4,
    slowdownRadius = 50,
    arrivalRadius = 5,
    stopSpeed = 0.5,
  },
  automation = {
    altitudeDeadband = 1.5,
    verticalScale = 12,
    thrustStartDistance = 8,
    thrustFullDistance = 50,
    steeringDeadband = 0.12,
    steeringScale = 0.8,
    steeringInvert = false,
    headingMinimumSpeed = 0.25,
    headingUnknownForwardRatio = 0,
  },
  orientation = {
    forward = { x = 0, y = 0, z = -1 },
    up = { x = 0, y = 1, z = 0 },
  },
  network = {
    enabled = false,
    channel = "cc-navtool",
    host = "navtool-aircraft",
    sharedKey = "",
  },
  outputs = {
    forward = { side = "front", analog = true, inverted = false, maximum = 5 },
    reverse = { side = "back", analog = true, inverted = false, maximum = 5 },
    left = { side = "left", analog = true, inverted = false, maximum = 5 },
    right = { side = "right", analog = true, inverted = false, maximum = 5 },
    up = { side = "top", analog = true, inverted = false, maximum = 5 },
    down = { side = "bottom", analog = true, inverted = false, maximum = 5 },
  },
}
