return {
  onboardingComplete = false,
  updateInterval = 0.05,
  sublevelEnabled = true,
  telemetryPeripheral = nil,
  orientationPeripheral = nil,
  navigationTablePeripheral = nil,
  gimbalSensorPeripheral = nil,
  altitudeSensorPeripheral = nil,
  physicsAssemblerPeripheral = nil,
  monitorPeripheral = nil,
  gps = {
    enabled = true,
    timeout = 0.5,
  },
  safety = {
    maximumOutput = 5,
    maximumRemotePulse = 2.0,
    disengageOnTelemetryLoss = true,
    clearOutputsOnExit = true,
  },
  navigation = {
    cruiseSpeed = 12,
    approachSpeed = 4,
    slowdownRadius = 50,
    arrivalRadius = 5,
    stopSpeed = 0.5,
  },
  automation = {
    altitudeDeadband = 1.5,
    verticalScale = 12,
    thrustStartDistance = 8,
    thrustFullDistance = 50,
    steeringDeadband = 0.12,
    steeringScale = 0.8,
    steeringInvert = false,
    headingMinimumSpeed = 0.25,
    headingUnknownForwardRatio = 0.25,
    outputHoldAfter = 0.6,
    outputPulseReleaseGrace = 0.25,
    outputHoldReleaseGrace = 1.0,
  },
  flightControl = {
    interval = 0.05,
    minimumThrustAlignment = 0.25,
    hoverVelocityGain = 0.18,
    headingPID = {
      kp = 1.6, ki = 0.02, kd = 0.45,
      minimum = -1, maximum = 1,
      integralMinimum = -0.5, integralMaximum = 0.5,
      derivativeFilter = 0.65,
    },
    altitudePID = {
      kp = 0.12, ki = 0.01, kd = 0.18,
      minimum = -1, maximum = 1,
      integralMinimum = -0.5, integralMaximum = 0.5,
      derivativeFilter = 0.65,
    },
    speedPID = {
      kp = 0.16, ki = 0.015, kd = 0.08,
      minimum = -1, maximum = 1,
      integralMinimum = -0.5, integralMaximum = 0.5,
      derivativeFilter = 0.65,
    },
    recorder = {
      enabled = true,
      flushInterval = 2,
      maximumBuffer = 40,
    },
  },
  orientation = {
    forward = { x = 0, y = 0, z = -1 },
    up = { x = 0, y = 1, z = 0 },
    yawFormat = "avionics",
    yawOffset = 0,
  },
  network = {
    enabled = false,
    channel = "cc-navtool",
    host = "navtool-aircraft",
    sharedKey = "",
  },
  outputs = {
    forward = { side = "front", analog = true, inverted = false, maximum = 5 },
    reverse = { side = "back", analog = true, inverted = false, maximum = 5 },
    left = { side = "left", analog = true, inverted = false, maximum = 5 },
    right = { side = "right", analog = true, inverted = false, maximum = 5 },
    up = { side = "top", analog = true, inverted = false, maximum = 5 },
    down = { side = "bottom", analog = true, inverted = false, maximum = 5 },
  },
}
